index:
#    path: /
#    controller: App\Controller\DefaultController::index
#  a decommenter ainsi que les deux lignes suivantes si besoin
    path : /article
    controller: App\Controller\ArticleController::article
